country = input("Enter name of country: ")
stateprovince = input("Enter name of province: ")
districtmunipality = input("Enter name of district / municipality: ")
locality = input("Enter name of town/village or any locality: ")
male = int(input("Enter male population: "))
female = int(input("Enter female population: "))
ratio = (female/male) * 1000
totalpopulation = female + male
print(" ")
print("COUNTRY: {} \n STATE/PROVINCE: {} \n DISTRICT/MUNICIPALITY: {} \n LOCALITY: {} \n".format(country,stateprovince,districtmunipality,locality))
print("MALE POPULATION: {} \n FEMALE POPULATION: {} \n".format(male,female))
print("RATIO (FEMALES PER ONE THOUSAND MALES): {:.0f} \n TOTAL POPULATION: {}".format(ratio,totalpopulation))
print(" ")
print("====SYSTEM TECHNICAL PRIMITIVE INFO====")
print(" ")
print("(COUNTRY/PROVINCE/DISTRICT/LOCALITY)\n ")
print("ONLY SPACES: ",country.isspace(),stateprovince.isspace(),districtmunipality.isspace(),locality.isspace())
print("NUMERIC: ",country.isnumeric(),stateprovince.isnumeric(),districtmunipality.isnumeric(),locality.isnumeric())
print("ALPHABETIC: ",country.isalpha(),stateprovince.isalpha(),districtmunipality.isalpha(),locality.isalpha())
print("ALPHANUMERIC: ",country.isalnum(),stateprovince.isalnum(),districtmunipality.isalnum(),locality.isalnum())